repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.11
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.6
  hooks:
  hooks:
    - id: uv-export
      name: main dependencies
      args: [--output-file, requirements.txt]
    - id: uv-lock