[project]
name = "dio-vectorial-databases"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.11.0.post1",
    "numpy>=2.3.1",
    "sentence-transformers>=5.0.0",
]
